### ISSUE TITLE
Mature content warning blocks previews

### ISSUE THREAD

**Issue by DS2902** [Previews-app/Previews#16]
Some channel previews contain a warning about adult content. This blocks viewing of the video and requires confirmation of consent to view. But it cannot be confirmed in the extension. Is it possible to add automatic confirmation?

**Comment by Previews-app** [comment]
due to the legality of the issue we cannot confirm it for you, however, i did add a delay for the preview so you can hover it and click the button.
if you can't click it in time for the delay, open the sidebar, hover over the streamer with the confirmation screen, then click the purple speaker icon that appears, you should now be able to hover over and confirm it.
