### ISSUE TITLE
[QoL Request] Toggle to preview with audio on.

### ISSUE THREAD

**Issue by niquilz** [Previews-app/Previews#30]
Usually I still get the "Preparing your stream" clip before a preview goes live.  

That's fine but when I click to enable preview audio one of two things usually occur:
If the "Preparing your stream" clip is currently in progress, it starts over.

If the stream is previewing live, it will kick me back to the "Preparing your stream" clip again.

This almost defeats the purpose of having a preview addon such as this because a quick hover-over popout to see what's going on is now a 15-30 second process that is likely going to start again if I bump my mouse a hair too far or just want to hear.  May as well just go on in at that point.

Thank you for reading, will donate again if something like this gets picked up.

**Comment by Previews-app** [comment]
that "preparing your stream" thingy really is annoying, i usually just look at the preview image before the video starts when that happens.

but regarding your question, we do have the toggle so you don't have to click the button (which i assume you're doing because it starts over).

![image](https://github.com/Previews-app/Previews/assets/90059485/ac3c5e6b-1f18-4197-84a6-55347b41685d)

a little tip i can give you is to change your preview size to a different size (bigger or smaller by at least 100px i think? not sure). this will make it that preview thumbnails are more up to date however they will take a little longer to show since twitch is generating a new thumbnail if there is none in their cache.
