### ISSUE TITLE
Preview image wont go away

### ISSUE THREAD

**Issue by ChristianMGO** [Previews-app/Previews#9]
Sometimes when hovering over streams (usually after clicking "Show more") the preview image locks up 
It fixes after reloading or going to vods/clips and hovering over them for a bit

**Example of the bug**
![PreviewGlitch](https://github.com/Previews-app/Previews/assets/53414839/ee05c9b9-aa42-4d70-849e-96cf00c53927)
(Preview locked bottom left when hovering another stream)

**Extensions enabled**
![PreviewExtensionsON](https://github.com/Previews-app/Previews/assets/53414839/2d182a88-7e26-4a79-825a-c872c10ec409)
(Dark Reader is not enabled on twitch)

Thank you for making the extension possible, its awesome

**Comment by Previews-app** [comment]
happens to me too sometimes, you could use the "auto extend sidebar" feature to mitigate this, or switch to a different tab and come back to the twitch tab and it should purge it.

**Comment by Previews-app** [comment]
happens due to twitch updating (replacing) the sidebar items during specific times causing the hover out receivers to be destroyed, added an X on the top right corner of the previews so we can close it when this happens very once in a while. the alternative to do this automatically might result in worse performance.
